[package]
name = "surface-control-tray"
version = "0.1.0"
authors = ["budde25 <ethan@ebudd.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gio = "0.9"
glib = "0.10"
gtk = "0.9"
libappindicator = "0.5"